version: "3.6"
services:
  core:
    build: .
    ports:
      - 8086:8080
    depends_on:
      - db
      - rabbit
    volumes:
      - /home/code/Server/storage:/app/tomcat/bin/storage
      - /home/code/.m2:/root/.m2

  db:
    image: mongo:latest
    ports:
      - 27013:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
        

  rabbit:
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15670:15672

volumes:
  mongodb:
  mongoconfig:

