version: "3.6"
services:
  core:
    build: 
      context: .
      dockerfile: ./docker/core.dockerfile
    container_name: codechar_server
    command: ["sleep","inf"]
    ports:
      - 8086:8080
    volumes:
      - /home/code/Server/storage:/tomcat/bin/storage
      - /home/code/.m2:/root/.m2
      - ./:/app

  db:
    build: 
      context: .
      dockerfile: ./docker/mongo.dockerfile
    container_name: codechar_mongo
    ports:
      - 27013:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    environment:
            MONGO_INITDB_DATABASE: codecharacter-2020
        

  rabbit:
    image: rabbitmq:3.5.3-management
    container_name: codechar_rabbit
    ports:
      - 5672:5672
      - 15670:15672

volumes:
  mongodb:
  mongoconfig:

